"""add user company_name (sender identity for AI compose)

Revision ID: 42646f566390
Revises: 1b9cd2d2b2ee
Create Date: 2026-07-30 18:47:00.757044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42646f566390'
down_revision: Union[str, Sequence[str], None] = '1b9cd2d2b2ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default backfills existing rows ("" = unset); the model's Python-side
    # default covers new rows.
    op.add_column(
        'users',
        sa.Column('company_name', sa.String(length=200), nullable=False, server_default=''),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'company_name')
    # ### end Alembic commands ###
